# Vectorization

In [2]:
import numpy as np 

In [1]:
def myfunc(a,b):
    if a > b:
        return -1
    else:
        return 1


In [4]:
vfunc = np.vectorize(myfunc)
vfunc

In [5]:
vfunc([1,2,3,3],2)

array([ 1,  1, -1, -1])

In [7]:
vfunc([1,2,3,4], [1,2,3,2])

array([ 1,  1,  1, -1])

In [57]:
# exmple 2
mynumpy = np.arange(100000)
# mymatrix = mymatrix = np.matrix('-1 0 1; -2 0 2; -4 0 4')
mymatrix = np.asmatrix(mynumpy)
print(mymatrix)

import math
def myfunc(z):
    return 1/(1+math.exp(-z))


[[    0     1     2 ... 99997 99998 99999]]


In [58]:
%%time 
vfunc = np.vectorize(myfunc) 
vfunc(mymatrix) # apply function to elementwise

Wall time: 83.8 ms


matrix([[0.5       , 0.73105858, 0.88079708, ..., 1.        , 1.        ,
         1.        ]])

In [59]:
%%time
flatten_matrix = np.asarray(mymatrix).flatten()
np.array(list(map(myfunc, flatten_matrix.tolist())))

Wall time: 59.8 ms


array([0.5       , 0.73105858, 0.88079708, ..., 1.        , 1.        ,
       1.        ])

In [3]:
vfunc1 = np.vectorize(lambda x: x+1) 
vfunc1

In [5]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
vfunc1(x)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])